# Generated by Django 5.2.10 on 2026-02-01 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('criacao', 'Criação'), ('avaliacao', 'Avaliação'), ('atribuicao_gerente', 'Atribuição de Gerente'), ('inicio_desenvolvimento', 'Início do Desenvolvimento'), ('evento', 'Evento'), ('pendencia', 'Pendência'), ('prioridade', 'Prioridade'), ('tag', 'Tag'), ('entrega', 'Entrega'), ('homologacao', 'Homologação'), ('adiamento_solicitado', 'Adiamento Solicitado'), ('adiamento_aprovado', 'Adiamento Aprovado'), ('adiamento_rejeitado', 'Adiamento Rejeitado')], max_length=30, verbose_name='Tipo de Evento')),
                ('data', models.DateTimeField(verbose_name='Data do Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='projects.project', verbose_name='Projeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Entrada da Timeline',
                'verbose_name_plural': 'Entradas da Timeline',
                'ordering': ['projeto', 'data'],
            },
        ),
    ]
