# Generated by Django 5.2.10 on 2026-02-01 17:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Card')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('bloqueado', 'Bloqueado')], default='pendente', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('desenvolvedor', models.ForeignKey(blank=True, limit_choices_to={'role': 'desenvolvedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Desenvolvedor')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['projeto', 'prioridade', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pendencia', 'Pendência'), ('prioridade', 'Prioridade'), ('tag', 'Tag'), ('comentario', 'Comentário')], max_length=20, verbose_name='Tipo de Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Evento')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.card', verbose_name='Card')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('em_avaliacao', 'Em Avaliação'), ('aprovado', 'Aprovado'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('entregue', 'Entregue'), ('homologado', 'Homologado'), ('adiado', 'Adiado')], default='criado', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Avaliação')),
                ('data_atribuicao_gerente', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atribuição do Gerente')),
                ('data_inicio_desenvolvimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início do Desenvolvimento')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('data_homologacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Homologação')),
                ('data_adiamento_solicitada', models.DateTimeField(blank=True, null=True, verbose_name='Data de Solicitação de Adiamento')),
                ('nova_data_prevista', models.DateField(blank=True, null=True, verbose_name='Nova Data Prevista')),
                ('adiamento_aprovado', models.BooleanField(default=False, verbose_name='Adiamento Aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('desenvolvedor', models.ForeignKey(blank=True, limit_choices_to={'role': 'desenvolvedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Desenvolvedor')),
                ('gerente_atribuido', models.ForeignKey(blank=True, limit_choices_to={'role': 'gerente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_managed', to=settings.AUTH_USER_MODEL, verbose_name='Gerente Atribuído')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='projects.project', verbose_name='Projeto'),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Sprint')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('duracao_dias', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duração em Dias')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='sprints_created', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.sprint', verbose_name='Sprint'),
        ),
    ]
