# Generated by Django 5.2.10 on 2026-02-01 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_sprint_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='desenvolvedor',
        ),
        migrations.AddField(
            model_name='card',
            name='area',
            field=models.CharField(choices=[('rpa', 'RPA'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('script', 'Script')], default='backend', max_length=20, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='card',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='card',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='card',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='card',
            name='tipo',
            field=models.CharField(choices=[('nova_robotizacao', 'Nova Robotização'), ('feature', 'Feature'), ('bug', 'Bug'), ('refact_completo', 'Refact Completo'), ('refact_pontual', 'Refact Pontual'), ('otimizacao_processo', 'Otimização de Processo'), ('melhoria_fluxo', 'Melhoria de Fluxo'), ('novo_script', 'Novo Script'), ('ferramenta', 'Ferramenta'), ('qualidade', 'Qualidade'), ('teste_software', 'Teste de Software'), ('raspagem_dados', 'Raspagem de Dados'), ('novo_painel', 'Novo Painel'), ('ia', 'IA'), ('auditoria', 'Auditoria')], default='feature', max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='card',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('absoluta', 'Absoluta')], default='media', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('a_desenvolver', 'A Desenvolver'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('parado_pendencias', 'Parado por Pendências'), ('em_homologacao', 'Em Homologação'), ('finalizado', 'Finalizado'), ('inviabilizado', 'Inviabilizado')], default='a_desenvolver', max_length=20, verbose_name='Status'),
        ),
    ]
