# Generated by Django 5.2.10 on 2026-02-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_card_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='script_url',
            field=models.URLField(blank=True, help_text='URL para o script de confecção do projeto', max_length=500, null=True, verbose_name='Link do Script'),
        ),
        migrations.AlterField(
            model_name='card',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição/Instruções'),
        ),
    ]
