# Generated by Django 5.2.10 on 2026-02-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_script_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='card',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
