# Generated by Django 5.2.10 on 2026-02-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_convert_card_dates_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='area',
            field=models.CharField(choices=[('rpa', 'RPA'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('script', 'Script'), ('sistema', 'Sistema')], default='backend', max_length=20, verbose_name='Área'),
        ),
    ]
