# Generated by Django 5.2.10 on 2026-02-04 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_create_cardlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlog',
            name='tipo_evento',
            field=models.CharField(choices=[('criado', 'Criado'), ('movimentado', 'Movimentado'), ('pendencia', 'Pendência'), ('atualizado', 'Atualizado'), ('alteracao', 'Alteração no Card'), ('responsavel_alterado', 'Responsável Alterado')], max_length=30, verbose_name='Tipo de Evento'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('card_created', 'Card Criado'), ('card_updated', 'Card Atualizado'), ('card_deleted', 'Card Deletado'), ('card_moved', 'Card Movido'), ('sprint_created', 'Sprint Criada'), ('project_created', 'Projeto Criado'), ('role_changed', 'Cargo Alterado'), ('card_overdue', 'Card Atrasado'), ('card_due_24h', 'Card Vence em 24h'), ('card_due_1h', 'Card Vence em 1h'), ('card_due_10min', 'Card Vence em 10min'), ('log_created', 'Log Criado')], max_length=30, verbose_name='Tipo de Notificação')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('card_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Card')),
                ('sprint_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Sprint')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Projeto')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['usuario', 'lida', '-data_criacao'], name='projects_no_usuario_9df5ec_idx'), models.Index(fields=['usuario', '-data_criacao'], name='projects_no_usuario_3faa3b_idx')],
            },
        ),
    ]
