# Generated by Django 5.2.10 on 2026-02-04 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_cardlog_tipo_evento_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPriorityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_limite', models.TimeField(default='09:00:00', verbose_name='Horário Limite (Sexta-feira)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração de Prioridade Semanal',
                'verbose_name_plural': 'Configurações de Prioridade Semanal',
            },
        ),
        migrations.CreateModel(
            name='WeeklyPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(help_text='Data da segunda-feira da semana', verbose_name='Início da Semana (Segunda-feira)')),
                ('semana_fim', models.DateField(help_text='Data da sexta-feira da semana', verbose_name='Fim da Semana (Sexta-feira)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_priorities', to='projects.card', verbose_name='Card')),
                ('definido_por', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['supervisor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_priorities_defined', to=settings.AUTH_USER_MODEL, verbose_name='Definido por')),
                ('usuario', models.ForeignKey(limit_choices_to={'role__in': ['gerente', 'desenvolvedor', 'dados']}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_priorities', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Prioridade Semanal',
                'verbose_name_plural': 'Prioridades Semanais',
                'ordering': ['-semana_inicio', 'usuario'],
                'unique_together': {('usuario', 'semana_inicio')},
            },
        ),
    ]
