# Generated by Django 5.2.10 on 2026-02-04 19:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_weeklypriorityconfig_weeklypriority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklypriority',
            unique_together={('usuario', 'card', 'semana_inicio')},
        ),
    ]
