# Generated by Django 5.2.10 on 2026-02-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_weeklypriority_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypriorityconfig',
            name='semana_fechada',
            field=models.JSONField(blank=True, default=dict, help_text='Dicionário com as semanas fechadas no formato {semana_inicio: True}', verbose_name='Semanas Fechadas'),
        ),
    ]
