# Generated by Django 5.2.10 on 2026-02-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_weeklypriorityconfig_semana_fechada'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='complexidade_custom_items',
            field=models.JSONField(blank=True, default=list, help_text='Array de objetos com id, label e hours dos itens personalizados criados pelo usuário', verbose_name='Itens Personalizados da Estimativa de Complexidade'),
        ),
        migrations.AddField(
            model_name='card',
            name='complexidade_selected_development',
            field=models.CharField(blank=True, help_text='ID do item de desenvolvimento selecionado na estimativa de complexidade', max_length=50, null=True, verbose_name='Desenvolvimento Selecionado na Estimativa'),
        ),
        migrations.AddField(
            model_name='card',
            name='complexidade_selected_items',
            field=models.JSONField(blank=True, default=list, help_text='Array de IDs dos itens selecionados na estimativa de complexidade', verbose_name='Itens Selecionados na Estimativa de Complexidade'),
        ),
    ]
