# Generated by Django 5.2.10 on 2026-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_fix_complexidade_notnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlog',
            name='tipo_evento',
            field=models.CharField(choices=[('criado', 'Card Criado'), ('movimentado', 'Movimentado'), ('pendencia', 'Pendência'), ('atualizado', 'Atualizado'), ('alteracao', 'Alteração no Card'), ('responsavel_alterado', 'Responsável Alterado')], max_length=30, verbose_name='Tipo de Evento'),
        ),
    ]
