# Generated by Django 5.2.10 on 2026-02-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_cardlog_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypriorityconfig',
            name='fechamento_automatico',
            field=models.BooleanField(default=True, help_text='Se habilitado, a semana será fechada automaticamente ao chegar no horário limite', verbose_name='Fechamento Automático'),
        ),
    ]
