# Generated by Django 5.2.10 on 2026-02-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_weeklypriorityconfig_fechamento_automatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_comment',
            field=models.TextField(blank=True, help_text='Comentário geral do card', null=True, verbose_name='Comentário do Card'),
        ),
        migrations.CreateModel(
            name='CardTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500, verbose_name='Texto do TODO')),
                ('is_original', models.BooleanField(default=False, help_text='Se é um TODO original criado automaticamente (não pode ser removido)', verbose_name='TODO Original')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('blocked', 'Bloqueado'), ('warning', 'Aviso')], default='pending', max_length=20, verbose_name='Status')),
                ('comment', models.TextField(blank=True, help_text='Comentário do TODO', null=True, verbose_name='Comentário')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição do TODO', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='projects.card', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'TODO do Card',
                'verbose_name_plural': 'TODOs dos Cards',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
