# Generated by Django 5.2.10 on 2026-02-06 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_card_card_comment_cardtodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou esta demanda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
    ]
