# Generated by Django 5.2.10 on 2026-02-06 19:00

from django.db import migrations
from django.contrib.auth import get_user_model


def populate_criado_por(apps, schema_editor):
    """Preenche o campo criado_por dos cards antigos com o primeiro admin ou supervisor disponível"""
    Card = apps.get_model('projects', 'Card')
    User = get_user_model()
    
    # Buscar primeiro admin ou supervisor disponível
    default_user = None
    try:
        default_user = User.objects.filter(role__in=['admin', 'supervisor'], is_active=True).first()
        if not default_user:
            # Se não houver admin/supervisor, usar o primeiro usuário ativo
            default_user = User.objects.filter(is_active=True).first()
    except Exception:
        # Se não conseguir buscar usuário, usar None (será null no banco)
        pass
    
    if default_user:
        # Atualizar todos os cards que não têm criado_por
        updated_count = Card.objects.filter(criado_por__isnull=True).update(criado_por=default_user)
        print(f'Preenchido criado_por para {updated_count} cards antigos com usuario: {default_user.username}')
    else:
        print('Nenhum usuario encontrado para preencher criado_por dos cards antigos')


def reverse_populate_criado_por(apps, schema_editor):
    """Reverter: definir criado_por como null para cards que foram preenchidos pela migration"""
    # Não fazemos nada na reversão, pois queremos manter os dados
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_add_criado_por_to_card'),
    ]

    operations = [
        migrations.RunPython(populate_criado_por, reverse_populate_criado_por),
    ]
