# Generated by Django 5.2.10 on 2026-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_populate_card_todos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('card_created', 'Card Criado'), ('card_updated', 'Card Atualizado'), ('card_deleted', 'Card Deletado'), ('card_moved', 'Card Movido'), ('card_todo_updated', 'TODO do Card Atualizado'), ('sprint_created', 'Sprint Criada'), ('project_created', 'Projeto Criado'), ('role_changed', 'Cargo Alterado'), ('card_overdue', 'Card Atrasado'), ('card_due_24h', 'Card Vence em 24h'), ('card_due_1h', 'Card Vence em 1h'), ('card_due_10min', 'Card Vence em 10min'), ('log_created', 'Log Criado')], max_length=30, verbose_name='Tipo de Notificação'),
        ),
    ]
