# Generated by Django 5.2.10 on 2026-02-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_notification_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='finalizada',
            field=models.BooleanField(default=False, verbose_name='Finalizada'),
        ),
    ]
