# Generated by Django 5.2.10 on 2026-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_add_sprint_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tipo',
            field=models.CharField(choices=[('nova_robotizacao', 'Nova Robotização'), ('feature', 'Feature'), ('bug', 'Bug'), ('refact_completo', 'Refact Completo'), ('refact_pontual', 'Refact Pontual'), ('otimizacao_processo', 'Otimização de Processo'), ('melhoria_fluxo', 'Melhoria de Fluxo'), ('novo_script', 'Novo Script'), ('ferramenta', 'Ferramenta'), ('qualidade', 'Qualidade'), ('teste_software', 'Teste de Software'), ('raspagem_dados', 'Raspagem de Dados'), ('novo_painel', 'Novo Painel'), ('ia', 'IA'), ('auditoria', 'Auditoria'), ('manutencao', 'Manutenção')], default='feature', max_length=30, verbose_name='Tipo'),
        ),
    ]
