# Generated by Django 5.2.10 on 2026-02-01 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Equipe')),
                ('tipo', models.CharField(choices=[('front', 'Frontend'), ('back', 'Backend'), ('custom', 'Customizado')], default='custom', max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='teams_supervised', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('desenvolvedor', models.ForeignKey(blank=True, limit_choices_to={'role': 'desenvolvedor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_hierarchies', to=settings.AUTH_USER_MODEL, verbose_name='Desenvolvedor')),
                ('gerente', models.ForeignKey(limit_choices_to={'role': 'gerente'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_hierarchies', to=settings.AUTH_USER_MODEL, verbose_name='Gerente')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_hierarchies', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Hierarquia',
                'verbose_name_plural': 'Hierarquias',
                'ordering': ['supervisor', 'gerente', 'desenvolvedor'],
                'unique_together': {('supervisor', 'gerente', 'desenvolvedor')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('gerente', 'Gerente'), ('desenvolvedor', 'Desenvolvedor')], default='desenvolvedor', max_length=20, verbose_name='Função na Equipe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team', verbose_name='Equipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros das Equipes',
                'ordering': ['team', 'role', 'user'],
                'unique_together': {('user', 'team')},
            },
        ),
    ]
