# Generated by Django 5.2.10 on 2026-02-02 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_hierarchy_gerente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='desenvolvedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['desenvolvedor', 'dados']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_hierarchies', to=settings.AUTH_USER_MODEL, verbose_name='Desenvolvedor'),
        ),
    ]
