# Generated by Django 5.2.10 on 2026-02-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_hierarchy_desenvolvedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='altura',
            field=models.FloatField(default=150, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='team',
            name='cor',
            field=models.CharField(default='yellow', max_length=20, verbose_name='Cor da Nota'),
        ),
        migrations.AddField(
            model_name='team',
            name='largura',
            field=models.FloatField(default=200, verbose_name='Largura'),
        ),
        migrations.AddField(
            model_name='team',
            name='posicao_x',
            field=models.FloatField(default=0, verbose_name='Posição X'),
        ),
        migrations.AddField(
            model_name='team',
            name='posicao_y',
            field=models.FloatField(default=0, verbose_name='Posição Y'),
        ),
    ]
