# Generated by Django 5.2.10 on 2026-02-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_add_sticky_note_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tipo',
            field=models.CharField(choices=[('portal', 'Portal'), ('rpa', 'RPA'), ('ia', 'IA'), ('dados', 'Dados'), ('processos', 'Processos'), ('front', 'Frontend'), ('back', 'Backend')], default='portal', max_length=20, verbose_name='Tipo'),
        ),
    ]
