# Generated by Django 5.2.10 on 2026-02-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('gerente', 'Gerente de Projetos'), ('desenvolvedor', 'Desenvolvedor'), ('dados', 'Dados')], default='desenvolvedor', max_length=20, verbose_name='Função'),
        ),
    ]
