# Generated by Django 5.2.10 on 2026-02-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('gerente', 'Gerente de Projetos'), ('desenvolvedor', 'Desenvolvedor'), ('dados', 'Dados'), ('processos', 'Processos')], default='desenvolvedor', max_length=20, verbose_name='Função'),
        ),
    ]
