# Generated by Django 5.2.10 on 2026-02-04 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeekDayDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sorteio', models.DateTimeField(auto_now_add=True, verbose_name='Data do Sorteio')),
                ('marcado_manual', models.BooleanField(default=False, help_text='Indica se foi marcado manualmente como sorteado', verbose_name='Marcado Manualmente')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('sorteado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geekday_draws_made', to=settings.AUTH_USER_MODEL, verbose_name='Sorteado Por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geekday_draws', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Sorteado')),
            ],
            options={
                'verbose_name': 'Sorteio Geek Day',
                'verbose_name_plural': 'Sorteios Geek Day',
                'ordering': ['-data_sorteio'],
                'unique_together': {('usuario', 'data_sorteio')},
            },
        ),
    ]
