# Generated by Django 5.2.10 on 2026-02-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekday', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='geekdaydraw',
            unique_together=set(),
        ),
    ]
