# Generated by Django 5.2.10 on 2026-02-01 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('em_avaliacao', 'Em Avaliação'), ('recusado', 'Recusado'), ('em_desenvolvimento', 'Em Desenvolvimento'), ('finalizado', 'Finalizado')], default='backlog', max_length=20, verbose_name='Status')),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Avaliação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('avaliado_por', models.ForeignKey(blank=True, limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_evaluated', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado Por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions_created', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Sugestão de Projeto',
                'verbose_name_plural': 'Sugestões de Projetos',
                'ordering': ['-created_at'],
            },
        ),
    ]
